-- =====================================================
-- Praktische Prüfungsversuche (ZP/AP) mit RLS
-- Regeln:
-- - Azubi: nur eigene Versuche sehen/anlegen
-- - Admin/Ausbilder: alle Versuche sehen/anlegen/ändern/löschen
-- =====================================================

CREATE TABLE IF NOT EXISTS public.practical_exam_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  exam_type TEXT NOT NULL CHECK (exam_type IN ('zwischen', 'abschluss')),
  average_grade NUMERIC(4,2),
  graded_count INTEGER NOT NULL DEFAULT 0 CHECK (graded_count >= 0),
  passed BOOLEAN,
  result_rows JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_by_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS practical_exam_attempts_user_created_idx
  ON public.practical_exam_attempts (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS practical_exam_attempts_type_created_idx
  ON public.practical_exam_attempts (exam_type, created_at DESC);

ALTER TABLE public.practical_exam_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Practical attempts select own or trainer/admin" ON public.practical_exam_attempts;
CREATE POLICY "Practical attempts select own or trainer/admin"
  ON public.practical_exam_attempts
  FOR SELECT
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'trainer')
        AND p.approved = true
    )
  );

DROP POLICY IF EXISTS "Practical attempts insert own or trainer/admin" ON public.practical_exam_attempts;
CREATE POLICY "Practical attempts insert own or trainer/admin"
  ON public.practical_exam_attempts
  FOR INSERT
  WITH CHECK (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'trainer')
        AND p.approved = true
    )
  );

DROP POLICY IF EXISTS "Practical attempts update trainer/admin only" ON public.practical_exam_attempts;
CREATE POLICY "Practical attempts update trainer/admin only"
  ON public.practical_exam_attempts
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'trainer')
        AND p.approved = true
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'trainer')
        AND p.approved = true
    )
  );

DROP POLICY IF EXISTS "Practical attempts delete trainer/admin only" ON public.practical_exam_attempts;
CREATE POLICY "Practical attempts delete trainer/admin only"
  ON public.practical_exam_attempts
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'trainer')
        AND p.approved = true
    )
  );
