import { BookOpen, Calculator, Droplets, FlaskConical, Heart, Languages, ShieldCheck, Wrench } from 'lucide-react';

export const LEARNING_CATEGORIES = [
  {
    id: 'bädertechnik',
    name: 'Bädertechnik',
    icon: '⚗️',
    lucideIcon: FlaskConical,
    description: 'Wasseraufbereitung, Anlagentechnik, Messtechnik',
    longDescription: 'Lerne den kompletten Wasserkreislauf eines Schwimmbads kennen: von der Überlaufrinne über Flockung, Filtration und Desinfektion bis zur Rücklaufeinspeisung. Interaktive 3D-Modelle zeigen dir jede Station im Detail.',
    paragraphs: '§3 Nr. 11–13',
    color: '#7c3aed',
    colorLight: '#7c3aed20',
    modules: [
      { id: 'water-cycle', name: 'Wasserkreislauf-Simulation', description: 'Interaktive Schwimmbad-Wasseraufbereitung mit 9 Stationen, 3D Deep Dives und Missionen', icon: '💧', available: true },
      { id: 'beckenarten-einrichtungen', name: 'Beckenarten & Einrichtungen', description: 'Übersicht zu Beckenformen, Ausstattung und Betriebseinrichtungen', icon: '🏗️', available: true },
      { id: 'startblock-startwand-bauliches', name: 'Startblock & Startwand (Bauliches)', description: 'Deep Dive mit 3D-Modell, Massen, Startwand und Rückenstart-Funktionen', icon: 'SB', available: true },
      { id: 'sprunganlagen', name: 'Sprunganlagen', description: 'Sprungturm, Bretter, Sicherheitsbereiche und Prüfpunkte', icon: '🏊‍♂️', available: true },
      { id: 'hubboden', name: 'Hubboden', description: 'Funktion, Sicherheit und Bedienung von Hubbodensystemen', icon: '⬆️', available: true },
      { id: 'ein-auswinterung', name: 'Ein- & Auswinterung', description: 'Saisonvorbereitung, Stilllegung und Wiederinbetriebnahme', icon: '❄️', available: true },
      { id: 'chemie-badewasser', name: 'Chemie der Badewasseraufbereitung', description: 'Unterthemen: Das Wasser, pH-Wert, Redox-Spannung, Saeuren und Basen, Oxidierbarkeit, Wasserhaerte, Korrosion und Korrosionsschutz', icon: '⚗️', available: true },
      { id: 'anlagen-badewasseraufbereitung', name: 'Anlagen Badewasseraufbereitung', description: 'Struktur und Zusammenspiel der zentralen Aufbereitungsstufen', icon: '🏭', available: true },
      { id: 'mess-und-regeltechnik', name: 'Mess- und Regeltechnik', description: 'Sensorik, Regler, Sollwerte und sicherer Anlagenbetrieb', icon: '📟', available: true },
      { id: 'pumpen', name: 'Pumpen', description: 'Umwälzpumpe im Schnittbild mit Hydraulik, Abdichtung, Service und Effizienz', icon: '⚙️', available: true },
      { id: 'membrandosierpumpe', name: 'Membrandosierpumpe', description: 'Magnet-Membrandosierpumpe mit Dosierhub, Hubverstellung und Steuerung im Schnittbild', icon: 'MD', available: true },
      { id: 'geschlossener-filter', name: 'Geschlossener Filter', description: 'Festbettfilter im Schnittbild mit Filterbett, Luftspuelung, Rueckspuelung und Wiederanfahren', icon: 'GF', available: true },
      { id: 'flockungsmittel', name: 'Flockungsmittel', description: 'Dosierung, Wirkung und Einbindung in den Prozess', icon: '🧫', available: true },
      { id: 'filtration-filtertechnik', name: 'Filtration & Filtertechnik', description: 'Filteraufbau, Schichtmaterialien und Filtrationsprinzipien', icon: '🗂️', available: true },
      { id: 'filterspuelung', name: 'Filterspuelung', description: 'Rueckspuelablauf mit Klappenstellungen fuer Filterspuelung, Ausserbetriebnahme und Inbetriebnahme', icon: 'FS', available: true },
      { id: 'desinfektionsverfahren', name: 'Desinfektionsverfahren', description: 'Verfahren und Betriebsgrenzen in der Badewasserdesinfektion', icon: '⚗️', available: true },
      { id: 'feststoff-chloranlage-calciumhypochlorid', name: 'Feststoff-Chloranlage (Calciumhypochlorid)', description: 'Deep Dive zur Calciumhypochlorit-Anlage mit Komponenten, Prozess und Betriebscheck', icon: '🧪', available: true },
      { id: 'chlorgasanlage-raum', name: 'Chlorgasanlage & Chlorgasraum', description: 'Sicherheitsanforderungen, Raumkonzept und Notfallmassnahmen', icon: '☢️', available: true },
      { id: 'uv-anlage', name: 'UV-Anlage', description: 'UV-Desinfektion, Wirkprinzip und Kombination mit Chlor', icon: '💡', available: true },
      { id: 'heizung-lueftung', name: 'Heizung & Lueftung', description: 'Wärmeuebertragung, Hallenklima und Entfeuchtung', icon: '🌬️', available: true },
    ],
  },
  {
    id: 'schwimmen',
    name: 'Schwimmen & Rettung',
    icon: '🏊',
    lucideIcon: Droplets,
    description: 'Schwimmtechniken, Rettungsschwimmen, Wasserrettung',
    longDescription: 'Schwimmtechniken trainieren, Rettungsszenarien üben und Abzeichen-Anforderungen kennenlernen. Von Brustschwimmen bis zur Rettungskette.',
    paragraphs: '§3 Nr. 8–9',
    color: '#0891b2',
    colorLight: '#0891b220',
    modules: [
      { id: 'schwimmtechniken', name: 'Schwimmtechniken', description: 'Brust, Kraul, Rücken und Delphin mit Technikschritten', icon: '🏊', available: true },
      { id: 'starts-wenden', name: 'Starts & Wenden', description: 'Startsprung, Rückenstart, Rollwende, Anschläge und Unterwasserphase', icon: '🚀', available: true },
      { id: 'rettungsgriffe', name: 'Rettungsgriffe', description: 'Anschwimmen, Befreiungsgriffe, Transportschwimmen und Bergung', icon: '🆘', available: true },
      { id: 'rettungsgeraete', name: 'Rettungsgeräte', description: 'Rettungsstange, Ring, Gurtretter, Wurfleine, Spineboard und O₂', icon: '🛟', available: true },
      { id: 'rettungskette', name: 'Rettungskette', description: 'Die 4 Glieder: Erkennen, Alarmieren, Bergen, Ersthelfen', icon: '⛑️', available: true },
      { id: 'rettungspruefung-fab', name: 'Rettungsschwimmer-Prüfung (FAB)', description: '300 m Ausdauer, kombinierte Übung mit Entkleiden, 50 m Schleppen, Tieftauchen, Streckentauchen — Anlehnung an die Bezirksregierung Düsseldorf', icon: '🥇', available: true },
      { id: 'wettkampf', name: 'Wettkampfschwimmen', description: 'Schwimmlagen, Rückenstartleine, Kampfrichter, Zeitnehmer, Regelwerk', icon: '🏆', available: true },
    ],
  },
  {
    id: 'erste-hilfe',
    name: 'Erste Hilfe & Gesundheitslehre',
    icon: '🚑',
    lucideIcon: Heart,
    description: 'HLW, Ersthelfer-Pflichten, Gesundheitslehre, Notfallmanagement',
    longDescription: 'Herz-Lungen-Wiederbelebung, stabile Seitenlage, Grundlagen der Gesundheitslehre und Umgang mit Badeunfällen speziell für den Bäderbetrieb.',
    paragraphs: '§3 Nr. 10',
    color: '#dc2626',
    colorLight: '#dc262620',
    modules: [
      { id: 'herz', name: 'Herz', description: 'Aufbau, Funktion und Rolle des Herzens im Kreislaufsystem', icon: '🫀', available: true },
      { id: 'blutkreislauf-gross-klein', name: 'Großer & kleiner Blutkreislauf', description: 'Weg des Blutes durch Körper- und Lungenkreislauf', icon: '🩸', available: true },
      { id: 'blut', name: 'Blut', description: 'Bestandteile, Blutgruppen, Gerinnung und Sauerstofftransport', icon: '🩸', available: true },
      { id: 'lunge-atmung', name: 'Lunge & Atemphysiologie', description: 'Aufbau, Atemvolumina, Gasaustausch und Atemregulation', icon: '🫁', available: true },
      { id: 'zellatmung', name: 'Zellatmung & Energiestoffwechsel', description: 'Aerob, anaerob, ATP, Laktat, Schwelle im Schwimmsport', icon: '⚡', available: true },
      { id: 'muskulatur', name: 'Muskulatur', description: 'Muskeltypen, Kontraktion, Krämpfe und Verletzungen', icon: '💪', available: true },
      { id: 'nervensystem', name: 'Nervensystem', description: 'ZNS/PNS, Neuron, Reflexe, vegetatives Nervensystem', icon: '🧠', available: true },
      { id: 'hyperventilation', name: 'Hyperventilation', description: 'Ursachen, Symptome und Erstmaßnahmen im Badebetrieb', icon: '🌬️', available: true },
      { id: 'haut', name: 'Die Haut', description: 'Schutzfunktion, Aufbau und Relevanz in der Ersten Hilfe', icon: '🧍', available: true },
      { id: 'sinnesorgane', name: 'Sinnesorgane', description: 'Auge, Ohr und weitere Sinne mit Bezug zu Badeunfaellen', icon: '👁️', available: true },
      { id: 'hlw-aed', name: 'HLW & AED', description: 'Algorithmus 30:2, Defibrillator und Teamablauf', icon: '❤️', available: true },
      { id: 'bewusstsein-atmung', name: 'Bewusstsein & Atmung', description: 'Ansprechen, Atemkontrolle und Entscheidungspfade', icon: '🫁', available: true },
      { id: 'stabile-seitenlage', name: 'Stabile Seitenlage', description: 'Sichere Lagerung und kontinuierliche Überwachung', icon: '🧍', available: true },
      { id: 'badeunfall-erstversorgung', name: 'Badeunfall-Erstversorgung', description: 'Typische Notfallbilder im Bad und Erstmassnahmen', icon: '🚑', available: true },
      { id: 'anaphylaxie', name: 'Anaphylaxie & allergischer Schock', description: 'Schweregrade, Symptome, Adrenalin-Autoinjektor, Wespenstich im Freibad', icon: '🐝', available: true },
      { id: 'hypoglykaemie', name: 'Hypoglykämie & Diabetes-Notfälle', description: 'Unterzucker erkennen, Verwechslung mit Bewusstlosigkeit vermeiden', icon: '🍬', available: true },
      { id: 'schock', name: 'Schock — Erkennung & Lagerung', description: 'Schockformen, Schockindex, richtige Lagerung, Maßnahmen', icon: '🩺', available: true },
      { id: 'verbrennungen', name: 'Verbrennungen & Sonnenbrand', description: 'Verbrennungsgrade, 9er-Regel, Erstmaßnahmen, UV-Schutz', icon: '🔥', available: true },
      { id: 'vergiftungen', name: 'Vergiftungen im Bäderbetrieb', description: 'Chlorgas, Chemikalien, Alkohol, Drogen, Giftnotruf-Zentralen', icon: '☣️', available: true },
      { id: 'wundversorgung', name: 'Wundversorgung & Druckverband', description: 'Wundarten, Blutungstypen, Druckverband Schritt für Schritt, Spezialfälle', icon: '🩹', available: true },
    ],
  },
  {
    id: 'bäderbetrieb',
    name: 'Bäderbetrieb',
    icon: '🔧',
    lucideIcon: Wrench,
    description: 'Betriebssicherheit, Aufsicht, Besucherbetreuung',
    longDescription: 'Verkehrssicherungspflicht, Aufsichtsplanung, Badeordnung, Besucherbetreuung und Konfliktlösung im täglichen Badebetrieb.',
    paragraphs: '§3 Nr. 5–7',
    color: '#9333ea',
    colorLight: '#9333ea20',
    modules: [
      { id: 'aufsicht-grundriss', name: 'Aufsicht im Grundriss', description: 'Aufsichtspositionen, Sichtlinien, Gefahrenzonen, DGUV 107-004', icon: '🗺️', available: true },
      { id: 'verkehrssicherung', name: 'Verkehrssicherungspflicht', description: 'Kontrollen, Haftung, Dokumentation und Maßnahmen bei Mängeln', icon: '⚠️', available: true },
      { id: 'betrieb-checklisten', name: 'Betriebs-Checklisten', description: 'Öffnungs-, Schicht- und Schließroutinen, Wasserqualität, Fristen', icon: '📋', available: true },
      { id: 'gaestekommunikation', name: 'Gästekommunikation', description: 'Deeskalation, Badeordnung durchsetzen, Beschwerdemanagement', icon: '🗣️', available: true },
    ],
  },
  {
    id: 'hygiene',
    name: 'Hygiene & Sicherheit',
    icon: '🧼',
    lucideIcon: ShieldCheck,
    description: 'Desinfektion, Gefahrstoffe, Arbeitsschutz',
    longDescription: 'Hygieneplan, Reinigungsmittel, Gefahrstoffverordnung, PSA und Arbeitssicherheit im Schwimmbad.',
    paragraphs: '§3 Nr. 4',
    color: '#eab308',
    colorLight: '#eab30820',
    modules: [
      { id: 'beschilderung-kennzeichnungen', name: 'Beschilderung & Kennzeichnungen', description: 'Sicherheitszeichen, Pflichtschilder und Orientierung im Bad', icon: '🪧', available: true },
      { id: 'reinigung-desinfektion', name: 'Reinigung & Desinfektion', description: 'Reinigungspläne, Verfahren, Kontaktzeiten, VAH/RKI-Listen, Hygieneplan-Vorlage', icon: '🧼', available: true },
      { id: 'gefahrstoffe', name: 'Gefahrstoffe', description: 'Lagerung, Handhabung, Schutzmaßnahmen und Notfallablauf', icon: '☣️', available: true },
      { id: 'legionellen-trinkwv', name: 'Legionellen & Trinkwasserverordnung', description: 'Vermehrung, TrinkwV-Pflichten, Probenahme, Maßnahmenwerte, DVGW W 551', icon: '🦠', available: true },
      { id: 'personalhygiene', name: 'Personalhygiene', description: 'Händehygiene, Berufskleidung, Hautschutz, Impfungen, IfSG-Belehrung', icon: '🧤', available: true },
      { id: 'lebensmittelhygiene', name: 'Lebensmittelhygiene', description: 'Imbiss/Kiosk im Bad, HACCP, Allergene, IfSG, Lebensmittelkontrolle', icon: '🍔', available: true },
      { id: 'stosschlorung', name: 'Stoßchlorung & Superchlorung', description: 'Anlässe, Mengenberechnung, Break-Point, DGfdB R 65.04 bei Stuhleintrag', icon: '⚗️', available: true },
    ],
  },
  {
    id: 'mathematik',
    name: 'Mathematik',
    icon: '123',
    lucideIcon: Calculator,
    description: 'Mathe, Physik und Betriebsrechnen fuer den Baederalltag in einfachen Schritten',
    longDescription: 'Von Grundrechenarten und Bruchrechnen ueber Geometrie, Bewegung, Druck, Waerme und Pumpen bis zur Chlor-Dosierung: Jeder Rechenweg wird einfach, mit Einheiten und mit Beispielen aus dem Baederbetrieb erklaert.',
    paragraphs: 'Lernhilfe · Grundlagen',
    color: '#0f766e',
    colorLight: '#0f766e20',
    modules: [
      { id: 'mathe-grundrechenarten', name: 'Grundrechenarten', description: 'Plus, Minus, Mal, Geteilt und Punkt-vor-Strich sicher anwenden', icon: '+-', available: true },
      { id: 'mathe-brueche', name: 'Bruchrechnen', description: 'Brueche addieren, erweitern, kuerzen und als Anteil lesen', icon: '1/2', available: true },
      { id: 'mathe-dreisatz', name: 'Dreisatz', description: 'Proportional und antiproportional — mit Baeder-Beispielen ausfuehrlich erklaert', icon: '3S', available: true },
      { id: 'mathe-prozent', name: 'Prozentrechnung', description: 'Anteile von 100 schnell und sauber berechnen', icon: '%', available: true },
      { id: 'mathe-formeln', name: 'Formeln & Buchstaben', description: 'Unbekannte groessen freistellen und mit Variablen rechnen', icon: 'x=', available: true },
      { id: 'mathe-pythagoras', name: 'Satz des Pythagoras', description: 'Rechtwinklige Dreiecke mit a2 + b2 = c2 berechnen', icon: 'a2', available: true },
      { id: 'mathe-flaechen', name: 'Flaechenberechnung', description: 'Rechteck, Dreieck und Kreis sauber berechnen', icon: 'm2', available: true },
      { id: 'mathe-volumen', name: 'Beckenvolumen', description: 'Laenge, Breite, Tiefe und Literumrechnung', icon: 'm3', available: true },
      { id: 'mathe-zeit', name: 'Zeit & Industriestunden', description: 'Normale Zeit sicher in Industriestunden umrechnen', icon: 'T', available: true },
      { id: 'mathe-auftrieb', name: 'Auftrieb', description: 'Warum Koerper schwimmen und wie Auftrieb grob berechnet wird', icon: 'FA', available: true },
      { id: 'mathe-druck', name: 'Druck', description: 'Flaeche, Kraft und Wasserdruck im Betrieb verstehen', icon: 'bar', available: true },
      { id: 'mathe-bewegung', name: 'Geschwindigkeit & Bewegung', description: 'Weg, Zeit und Geschwindigkeit sicher umrechnen', icon: 'v', available: true },
      { id: 'mathe-waerme', name: 'Waermelehre', description: 'Temperatur, Temperaturdifferenz und Waermemenge einfach erklaert', icon: 'Q', available: true },
      { id: 'mathe-mechanik', name: 'Mechanik', description: 'Kraft, Arbeit und Leistung fuer den technischen Alltag', icon: 'M', available: true },
      { id: 'mathe-pumpen', name: 'Pumpenberechnung', description: 'Foerderstrom, Foerderhoehe und Leistung in Grundschritten', icon: 'P', available: true },
      { id: 'mathe-filtration', name: 'Filtrationsberechnung', description: 'Filterflaeche, Filtrationsgeschwindigkeit und Auslegung', icon: 'VF', available: true },
      { id: 'mathe-chlor', name: 'Chlor-Dosierung', description: 'mg/L, m3 und Produktmenge im Becken sauber berechnen', icon: 'Cl', available: true },
      { id: 'mathe-formelsammlung', name: 'Formelsammelblatt', description: 'Wichtige Formeln aus Mathematik, Technik und Wasseraufbereitung', icon: 'FS', available: true },
      { id: 'mathe-mischrechnung', name: 'Mischrechnung & Frischwasser', description: 'Mischungskreuz, Konzentrationsausgleich, Frischwasservorgabe nach DIN 19643 (30 L/Gast)', icon: 'MX', available: true },
      { id: 'mathe-verdunstung', name: 'Verdunstung', description: 'Verdunstungsmengen, Mörl-Formel, Energieverlust, Reduktionsmaßnahmen', icon: '💨', available: true },
      { id: 'mathe-schwallwasser', name: 'Schwallwasser & Zirkulation', description: 'Ausgleichsbehälter, Personenverdrängung 50 L, Belastungs- vs. Umwälzzeit-bezogene Q nach DIN 19643', icon: '🌊', available: true },
    ],
  },
  {
    id: 'chemie',
    name: 'Chemie-Grundlagen',
    icon: 'H2O',
    lucideIcon: FlaskConical,
    description: 'Formeln lesen, Elemente erkennen und Stoffe aus dem Baederbetrieb verstehen',
    longDescription: 'Hier lernst du chemische Formeln wirklich von Grund auf. Du erkennst Elementsymbole, liest Zahlen und Klammern richtig und zerlegst typische Stoffe aus der Badewasseraufbereitung Schritt fuer Schritt.',
    paragraphs: 'Lernhilfe · Chemie',
    color: '#2563eb',
    colorLight: '#2563eb20',
    modules: [
      { id: 'chemische-formeln', name: 'Chemische Formeln verstehen', description: 'Buchstaben, Zahlen und Klammern in Formeln ganz einfach lesen', icon: 'CF', available: true },
      { id: 'stoffnamen-formeln', name: 'Stoffnamen & Formeln', description: 'Wie Stoffname, Formel und Einsatz zusammengehoeren', icon: 'SF', available: true },
      { id: 'saeuren-basen-grundlagen', name: 'Saeuren & Basen', description: 'Einfache Grundlagen zu pH, Saeuren und Basen', icon: 'pH', available: true },
      { id: 'redox-grundlagen', name: 'Redox-Grundlagen', description: 'Oxidation und Reduktion ohne Fachchinesisch', icon: 'Rx', available: true },
      { id: 'saeurekapazitaet', name: 'Säurekapazität & Wasserhärte', description: 'KS4,3-Wert, Härtegrade und Pufferwirkung im Beckenwasser', icon: 'KS', available: true },
      { id: 'beckenwasserdesinfektion', name: 'Beckenwasserdesinfektion', description: 'Chlor, UV, Ozon und Kombinationsverfahren nach DIN 19643', icon: 'Cl', available: true },
      { id: 'elektrolyse', name: 'Elektrolyse', description: 'Chlor aus Salz erzeugen — Inline, Side-Stream und Membranzelle', icon: 'El', available: true },
      { id: 'elektrolyse-3d', name: 'Elektrolysezelle (3D)', description: 'Interaktives 3D-Schnittbild einer Membranzellenelektrolyse mit Hotspots', icon: '⚡', available: true },
      { id: 'korrosion', name: 'Korrosion & Korrosionsschutz', description: 'Korrosionsarten erkennen und Metalle im Schwimmbad schuetzen', icon: 'Fe', available: true },
    ],
  },
  {
    id: 'english',
    name: 'Englisch im Bäderalltag',
    icon: '🇬🇧',
    lucideIcon: Languages,
    description: 'Fach-Englisch für Kasse, Aufsicht und Gäste — von Basics bis Berufspraxis',
    longDescription: 'Englisch ist im Bäderalltag real gefragt: Gäste an der Kasse, Wegauskünfte, Regeln durchsetzen, Notfall-Kommunikation. Die Lektionen bauen aufeinander auf (A1 → A2 → B1) — jede mit Vokabeln, echten Dialogen und Mini-Quiz.',
    paragraphs: 'Lernhilfe · Sprache',
    color: '#4f46e5',
    colorLight: '#4f46e520',
    modules: [
      { id: 'english-a1-alphabet', name: 'Das Alphabet & Aussprache', description: 'Englisches Alphabet mit Lautschrift, typische Stolperfallen und Namen buchstabieren', icon: 'Aa', level: 'A1', available: true },
      { id: 'english-a1-numbers-time', name: 'Zahlen, Uhrzeit & Datum', description: 'Zahlen 0–1000, Uhrzeit-Regeln, Öffnungszeiten und Eintrittspreise auf Englisch', icon: '123', level: 'A1', available: true },
      { id: 'english-a1-greetings', name: 'Begrüßung & Smalltalk', description: 'Sich vorstellen, höflich bleiben, Standardfloskeln für den Kundenkontakt', icon: '👋', level: 'A1', available: true },
      { id: 'english-a1-pool-basics', name: 'Im Schwimmbad — Basiswortschatz', description: 'Räume, Personen, Ausstattung und typische Schilder rund ums Bad', icon: '🏊', level: 'A1', available: true },
      { id: 'english-a2-guests', name: 'Gäste begrüßen & Eintritt verkaufen', description: 'Vollständige Kassen-Dialoge, Tarife erklären, Sonderwünsche behandeln', icon: '🎫', level: 'A2', available: true },
      { id: 'english-a2-directions', name: 'Wegbeschreibung im Bad', description: 'Wege erklären, Stockwerke, Richtungen — klar und missverständnisfrei', icon: '🧭', level: 'A2', available: true },
      { id: 'english-a2-rules', name: 'Hausordnung & Regeln erklären', description: 'Hausordnung durchsetzen, Regeln freundlich aber bestimmt kommunizieren', icon: '📋', level: 'A2', available: true },
      { id: 'english-b1-first-aid', name: 'Erste Hilfe auf Englisch', description: 'Kritische Notfall-Phrasen: Ansprache, Symptome abfragen, Rettungsdienst alarmieren', icon: '🚑', level: 'B1', available: true },
      { id: 'english-b1-complaints', name: 'Beschwerden & schwierige Gespräche', description: 'Deeskalation, Hausverbot, Versicherungsfälle, Reklamationen', icon: '💬', level: 'B1', available: true },
      { id: 'english-b1-tech-chemistry', name: 'Technik- & Chemie-Begriffe', description: 'Fachwortschatz: Chlorung, pH-Wert, Filtration, Wartung auf Englisch', icon: '⚗️', level: 'B1', available: true },
    ],
  },
  {
    id: 'verwaltung',
    name: 'Verwaltung & Recht',
    icon: '📝',
    lucideIcon: BookOpen,
    description: 'Berufsbildung, Arbeitsrecht, Kassenwesen',
    longDescription: 'Ausbildungsvertrag, Tarifrecht, Kassensysteme, Datenschutz und Öffentlichkeitsarbeit für den Bäderbetrieb.',
    paragraphs: '§3 Nr. 1–3, 14–15',
    color: '#059669',
    colorLight: '#05966920',
    modules: [
      { id: 'berufsrecht-basis', name: 'Berufsrecht-Basis', description: 'Ausbildungsvertrag, Rechte & Pflichten, Mitbestimmung, TVöD', icon: '📘', available: true },
      { id: 'pflichten-ag-an-ausbilder', name: 'AG · AN · Ausbilder · Azubi — Pflichten im Detail', description: 'BGB, BBiG, AEVO, GewO: Wer hat welche Rechte und Pflichten? Plus innerbetrieblicher Schadensausgleich', icon: '⚖️', available: true },
      { id: 'dienstplanung-arbeitszeit', name: 'Dienstplanung & Arbeitszeit', description: 'ArbZG, Schichtmodelle, Dienstplan, Zeitkonten, Feiertage', icon: '🗓️', available: true },
      { id: 'kasse-abrechnung', name: 'Kasse & Abrechnung', description: 'Kassenbuch, Ticketsysteme, Tagesabschluss, Buchführung', icon: '💳', available: true },
      { id: 'datenschutz-oea', name: 'Datenschutz & Öffentlichkeitsarbeit', description: 'DSGVO, Videoüberwachung, PR vs. Werbung, Social Media', icon: '📣', available: true },
      { id: 'strafrecht-bad-vertieft', name: 'Strafrecht im Bad — Vertiefung', description: 'Körperverletzung (§223–229), Diebstahl, Voyeurismus (§201a), Hausfriedensbruch, Sachbeschädigung', icon: '⚖️', available: true },
      { id: 'notwehr-nothilfe', name: 'Notwehr, Nothilfe & Notstand', description: '§32 Notwehr, §34/35 Notstand, §323c Hilfeleistung, §127 StPO Jedermanns-Festnahme', icon: '🛡️', available: true },
      { id: 'personalfuehrung', name: 'Personalführung im Bäderbetrieb', description: 'Organigramm, Führungsstile, Betriebsklima, Mobbing, Dienstplanung', icon: '👔', available: true },
      { id: 'rechtsnormen', name: 'Rechtsnormen & Rechtsaufbau', description: 'Normenhierarchie, Gerichtssystem, EU-Recht, öffentliches Recht vs. Zivilrecht', icon: '📜', available: true },
      { id: 'badevertrag-hausordnung', name: 'Badevertrag & Hausordnung', description: 'Konkludenter Vertragsschluss, Haus- & Badeordnung als AGB, Rechte & Pflichten, Hausverbot', icon: '🤝', available: true },
      { id: 'aufsichtspflicht', name: 'Aufsichts- & Verkehrssicherungspflicht', description: 'Betriebsaufsicht, Beckenaufsicht, DGUV 107-004, Dokumentationspflichten, Dienstkleidung', icon: '👁️', available: true },
      { id: 'gewaltenteilung', name: 'Gewaltenteilung & Staatsrecht', description: 'Legislative, Exekutive, Judikative — Behörden im Bäderbetrieb', icon: '🏛️', available: true },
      { id: 'strafrecht-bad', name: 'Strafrecht im Schwimmbad', description: '§323c StGB, Garantenstellung, Fahrlässigkeit, Verkehrssicherungspflicht', icon: '⚖️', available: true },
      { id: 'jugendarbeitsschutz', name: 'Jugendarbeitsschutzgesetz', description: 'Arbeitszeiten, Verbote und Ausnahmen für Jugendliche (JArbSchG)', icon: '👶', available: true },
      { id: 'mutterschutz', name: 'Mutterschutz & Elternzeit', description: 'MuSchG, Beschäftigungsverbote, Elternzeit nach BEEG', icon: '🤰', available: true },
      { id: 'kuendigung', name: 'Kündigung im Arbeitsrecht', description: 'Ordentliche & außerordentliche Kündigung, Abmahnung, KSchG', icon: '📄', available: true },
      { id: 'kommunalpolitik', name: 'Kommunalpolitik', description: 'Gemeindeorgane, Haushalt, kommunale Bäder — Daseinsvorsorge & Querfinanzierung', icon: '🏛️', available: true },
      { id: 'gesellschaftsformen', name: 'Gesellschaftsformen', description: 'GbR, OHG, KG, GmbH, AG — Rechtsformen und ihre Bedeutung für kommunale Bäder', icon: '🏦', available: true },
      { id: 'sozialversicherung', name: 'Sozialversicherung', description: 'Die 5 Säulen: Kranken-, Renten-, Unfall-, Pflege-, Arbeitslosenversicherung', icon: '🛡️', available: true },
      { id: 'kostenmanagement', name: 'Kostenmanagement & Bäderkasse', description: 'Kostenarten, Kalkulation, Bäderkasse, Controlling, Kostendeckungsgrad', icon: '💰', available: true },
      { id: 'marketing', name: 'Marketing im Bäderbetrieb', description: 'SWOT-Analyse, 4P-Mix, Zielgruppen, Öffentlichkeitsarbeit, Datenschutz', icon: '📣', available: true },
    ],
  },
];
