/**
 * This file is generated by server/scripts/generate-exam-assets.mjs.
 * Do not edit manually; regenerate from the frontend source question bank.
 */

export const PRACTICAL_EXAM_TYPES = [
  {
    "id": "zwischen",
    "label": "Zwischenprüfung",
    "icon": "ZP"
  },
  {
    "id": "abschluss",
    "label": "Abschlussprüfung",
    "icon": "AP"
  }
] as const;

export const PRACTICAL_SWIM_EXAMS = {
  "zwischen": [
    {
      "id": "zp_400m",
      "name": "400m ZP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 07:45",
      "gradingTable": [
        {
          "maxSeconds": 468,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 534,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 618,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 720,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": 840,
          "grade": 5,
          "noteLabel": "mangelhaft"
        },
        {
          "maxSeconds": null,
          "grade": 6,
          "noteLabel": "ungenügend"
        }
      ]
    },
    {
      "id": "zp_100m",
      "name": "100m ZP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 01:52",
      "gradingTable": [
        {
          "maxSeconds": 79.8,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 83.5,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 88.7,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 95,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": 102.4,
          "grade": 5,
          "noteLabel": "mangelhaft"
        },
        {
          "maxSeconds": null,
          "grade": 6,
          "noteLabel": "ungenügend"
        }
      ]
    },
    {
      "id": "zp_50m_transport",
      "name": "50m Transport ZP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 01:20",
      "gradingTable": [
        {
          "maxSeconds": 64.8,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 71.4,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 79.8,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 90,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": 102,
          "grade": 5,
          "noteLabel": "mangelhaft"
        },
        {
          "maxSeconds": null,
          "grade": 6,
          "noteLabel": "ungenügend"
        }
      ]
    },
    {
      "id": "zp_30m_tauch",
      "name": "30m Streckentauchen ZP",
      "inputType": "time_distance",
      "inputPlaceholder": "z. B. 00:33,6",
      "distancePlaceholder": "Strecke in m (z. B. 30)",
      "gradingTable": [
        {
          "maxSeconds": 26.7,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 30,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 34.2,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": null,
          "grade": 4,
          "noteLabel": "ausreichend"
        }
      ]
    },
    {
      "id": "zp_hlw",
      "name": "HLW-Prüfbogen",
      "inputType": "grade",
      "inputPlaceholder": "z. B. 2",
      "required": false,
      "gradingTable": []
    }
  ],
  "abschluss": [
    {
      "id": "ap_300m_kleiderschwimmen",
      "name": "300m Kleiderschwimmen AP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 06:20,1",
      "gradingTable": [
        {
          "maxSeconds": 366.6,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 399,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 434.1,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 480,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": null,
          "grade": 5,
          "noteLabel": "mangelhaft"
        }
      ]
    },
    {
      "id": "ap_100m",
      "name": "100m AP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 01:25,2",
      "gradingTable": [
        {
          "maxSeconds": 75.7,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 79.5,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 84.2,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 90,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": 98,
          "grade": 5,
          "noteLabel": "mangelhaft"
        },
        {
          "maxSeconds": null,
          "grade": 6,
          "noteLabel": "ungenügend"
        }
      ]
    },
    {
      "id": "ap_50m_abschleppen",
      "name": "50m Abschleppen AP",
      "inputType": "time",
      "inputPlaceholder": "z. B. 01:43,2",
      "gradingTable": [
        {
          "maxSeconds": 90.6,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 98.3,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 108.8,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": 120,
          "grade": 4,
          "noteLabel": "ausreichend"
        },
        {
          "maxSeconds": null,
          "grade": 5,
          "noteLabel": "mangelhaft"
        }
      ]
    },
    {
      "id": "ap_35m_tauch",
      "name": "35m Streckentauchen AP",
      "inputType": "time_distance",
      "inputPlaceholder": "z. B. 00:33,6",
      "distancePlaceholder": "Strecke in m (z. B. 35)",
      "gradingTable": [
        {
          "maxSeconds": 26.7,
          "grade": 1,
          "noteLabel": "sehr gut"
        },
        {
          "maxSeconds": 30,
          "grade": 2,
          "noteLabel": "gut"
        },
        {
          "maxSeconds": 34.2,
          "grade": 3,
          "noteLabel": "befriedigend"
        },
        {
          "maxSeconds": null,
          "grade": 4,
          "noteLabel": "ausreichend"
        }
      ]
    }
  ]
} as const;
